table 'Product Categories Lookup'
	excludeFromModelRefresh
	lineageTag: 92086a58-8686-4730-a517-32a86d26a928

	column ProductCategoryKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 251cf09c-efca-425a-ab1a-b7c30da990c7
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: f5eae25e-8e6e-4175-bf0a-76a40847e4b5
		summarizeBy: none
		sourceColumn: CategoryName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Product Categories Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("G:\All_My_Projects\PowerBiProject\AdventureWorks Product Categories Lookup.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductCategoryKey", Int64.Type}, {"CategoryName", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

