table 'Product Subcategories Lookup'
	excludeFromModelRefresh
	lineageTag: 445a780e-2444-47e3-9152-9dde8ef89f8a

	column ProductSubcategoryKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 816eb812-2570-44c5-a1c3-ab9bd59d8f6f
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SubcategoryName
		dataType: string
		lineageTag: f1b7578a-d87c-456d-a2bb-24b47a4ea7cf
		summarizeBy: none
		sourceColumn: SubcategoryName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 9bf4614c-7fd6-4710-8618-396068b84a95
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Product Subcategories Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("G:\All_My_Projects\PowerBiProject\AdventureWorks Product Subcategories Lookup.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductSubcategoryKey", Int64.Type}, {"SubcategoryName", type text}, {"ProductCategoryKey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

