table 'Returns Data'
	lineageTag: 7810ace8-e88e-430f-abc2-4854ea5b2b3c

	column ReturnDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8dce3daf-de63-4321-b3b3-566c0e9bf548
		summarizeBy: none
		sourceColumn: ReturnDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: 14a09f21-3e2d-4f6f-8a1a-a77ba7bff5d1
		summarizeBy: none
		sourceColumn: TerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: f975bfde-ba3f-4522-9881-26ff354bfaa7
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ReturnQuantity
		dataType: int64
		formatString: 0
		lineageTag: 8aefab5d-2399-4b7d-8d9e-6d9567975b49
		summarizeBy: sum
		sourceColumn: ReturnQuantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Returns Data' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("G:\All_My_Projects\PowerBiProject\AdventureWorks Returns Data.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ReturnDate", type date}, {"TerritoryKey", Int64.Type}, {"ProductKey", Int64.Type}, {"ReturnQuantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

