table 'Sales Data'
	lineageTag: 19aaadbb-8690-4604-bf80-1c1f35cfae1c

	column OrderDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: b1266d64-d744-43ec-8472-4327a756eeb0
		summarizeBy: none
		sourceColumn: OrderDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StockDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 914aa0c0-6152-4ab6-b796-20f188699c2b
		summarizeBy: none
		sourceColumn: StockDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderNumber
		dataType: string
		lineageTag: e0c045af-fb5e-46ae-a05b-723af984a947
		summarizeBy: none
		sourceColumn: OrderNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: d0e65a93-63a5-435a-8b5c-90179e48a961
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: e42b160c-77fd-4b6e-b1f8-901e91797f96
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: e1ea86dc-68ac-4c2b-bec6-d75fc2e2f6b4
		summarizeBy: none
		sourceColumn: TerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderLineItem
		dataType: int64
		formatString: 0
		lineageTag: 81341341-4999-4b3b-821a-16d80649f9c8
		summarizeBy: sum
		sourceColumn: OrderLineItem

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: c3770612-366b-4c34-90f0-23b9bb7ba612
		summarizeBy: sum
		sourceColumn: OrderQuantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Quantity Type' =
			
			IF(
			    'Sales Data'[OrderQuantity] > 1,
			    "Multiple Items",
			    "Single Item"
			)
		lineageTag: 897d277f-a1a3-4b27-9aee-adbd299c7c83
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Months Since First Transaction' =
			
			DATEDIFF(
			    RELATED('Customers Cohort'[First Transaction Month]),
			    RELATED('Calendar Lookup'[Start of Month]),
			    MONTH
			)
		formatString: 0
		lineageTag: 4094623c-85d2-4044-8474-55a31fb5c60c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Sales Data' = m
		mode: import
		source =
				let
				    Source = Folder.Files("G:\All_My_Projects\PowerBiProject\Sales Data"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"OrderDate", type date}, {"StockDate", type date}, {"OrderNumber", type text}, {"ProductKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"TerritoryKey", Int64.Type}, {"OrderLineItem", Int64.Type}, {"OrderQuantity", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Source.Name"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"OrderDate", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

